name: GitHub Release

on:
  push:
    branches: [release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Build Project
        uses: borales/actions-yarn@v4
        with:
          cmd: release

      - name: Identify Version Number
        id: version
        run: echo "::set-output name=version::$(node ./build/version.js)"

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: true
          release_name: ${{ steps.version.outputs.version }}
          tag_name: release-${{ steps.version.outputs.version }}
          body_path: CHANGELOG.md

      - name: Upload manifest.json
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/system.json
          asset_name: manifest.json
          asset_content_type: application/json

      - name: Upload System Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./genesys-${{ steps.version.outputs.version }}.zip
          asset_name: genesys-${{ steps.version.outputs.version }}.zip
          asset_content_type: application/zip
